/**
 * Chrome extension installer for Dev-Lens.
 *
 * Downloads a .crx3 file from Google's CDN, strips the CRX header to obtain
 * the embedded ZIP, extracts it to userData/installed-extensions/{id}/, and
 * loads it into the requested Electron sessions via session.loadExtension().
 *
 * MV3 compatibility:
 *   Electron does not implement chrome.webNavigation, chrome.contextMenus,
 *   chrome.notifications, or chrome.privacy.  When a MV3 service-worker
 *   background script tries to access these at top level it throws an
 *   uncaught error, which prevents the service worker from registering
 *   (Chromium status code 15).  We patch the service-worker file on disk by
 *   prepending no-op stubs for those APIs before Electron ever runs it.
 *   The stub is idempotent (detected by a sentinel comment).
 *
 * On startup, loadAllInstalledExtensions() re-loads every previously installed
 * extension from disk (patching any not yet patched).
 */
import fs from 'node:fs';
import path from 'node:path';
import https from 'node:https';
import http from 'node:http';
import { app } from 'electron';
import type { Session } from 'electron';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const AdmZip = require('adm-zip') as new (buf: Buffer) => {
  extractAllTo(dir: string, overwrite: boolean): void;
};

function extensionsDir(): string {
  return path.join(app.getPath('userData'), 'installed-extensions');
}

function crxDownloadUrl(extensionId: string): string {
  // Use the actual Chromium major version bundled with this Electron build.
  const major = (process.versions.chrome ?? '130').split('.')[0];
  return (
    'https://clients2.google.com/service/update2/crx' +
    `?response=redirect&prodversion=${major}.0.0.0&acceptformat=crx3` +
    `&x=id%3D${extensionId}%26uc`
  );
}

async function fetchWithRedirects(url: string, depth = 0): Promise<Buffer> {
  if (depth > 8) throw new Error('Too many redirects');
  const chromeMajor = (process.versions.chrome ?? '130').split('.')[0];
  return new Promise<Buffer>((resolve, reject) => {
    const proto = url.startsWith('https') ? https : http;
    proto
      .get(
        url,
        {
          headers: {
            'User-Agent': `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/${chromeMajor}.0.0.0 Safari/537.36`,
          },
        },
        (res) => {
          if (
            res.statusCode !== undefined &&
            res.statusCode >= 300 &&
            res.statusCode < 400 &&
            res.headers.location
          ) {
            resolve(fetchWithRedirects(res.headers.location, depth + 1));
            res.resume();
            return;
          }
          if (res.statusCode !== 200) {
            reject(new Error(`HTTP ${res.statusCode ?? 'unknown'} for ${url}`));
            res.resume();
            return;
          }
          const chunks: Buffer[] = [];
          res.on('data', (c: Buffer) => chunks.push(c));
          res.on('end', () => resolve(Buffer.concat(chunks)));
          res.on('error', reject);
        },
      )
      .on('error', reject);
  });
}

/**
 * Strip the CRX2/CRX3 header and return the raw ZIP bytes.
 */
function crxToZip(buf: Buffer): Buffer {
  const magic = buf.toString('ascii', 0, 4);
  if (buf[0] === 0x50 && buf[1] === 0x4b) return buf; // already a ZIP
  if (magic !== 'Cr24') throw new Error(`Unrecognised CRX magic: ${JSON.stringify(magic)}`);

  const version = buf.readUInt32LE(4);
  if (version === 3) {
    const headerSize = buf.readUInt32LE(8);
    return buf.subarray(12 + headerSize);
  }
  if (version === 2) {
    const pkLen = buf.readUInt32LE(8);
    const sigLen = buf.readUInt32LE(12);
    return buf.subarray(16 + pkLen + sigLen);
  }
  throw new Error(`Unknown CRX version: ${version}`);
}

/**
 * Chrome API stubs prepended to MV3 service-worker files.
 * These fill in the APIs that Electron does not implement so the service
 * worker can register without throwing at startup.
 * Kept as minimal no-ops — they silence crashes, not restore full behaviour.
 */
const ELECTRON_COMPAT_STUB = `// __devlens_electron_patched__
// Auto-generated by Dev-Lens: no-op stubs for Chrome APIs not implemented in Electron.
(function(){
  var _noop=function(){};
  var _event={addListener:_noop,removeListener:_noop,hasListeners:function(){return false;}};
  if(!chrome.webNavigation){chrome.webNavigation={
    onBeforeNavigate:_event,onCommitted:_event,onDOMContentLoaded:_event,
    onCompleted:_event,onErrorOccurred:_event,onCreatedNavigationTarget:_event,
    onReferenceFragmentUpdated:_event,onTabReplaced:_event,
    onHistoryStateUpdated:_event,
    getFrame:function(d,cb){if(typeof cb==='function')cb(null);return Promise.resolve(null);},
    getAllFrames:function(d,cb){if(typeof cb==='function')cb([]);return Promise.resolve([]);}
  };}
  if(!chrome.contextMenus){chrome.contextMenus={
    create:function(){return 0;},update:_noop,remove:_noop,removeAll:_noop,
    onClicked:_event,onShown:_event,onHidden:_event
  };}
  if(!chrome.notifications){chrome.notifications={
    create:function(id,o,cb){if(typeof cb==='function')cb(typeof id==='string'?id:'');},
    update:function(id,o,cb){if(typeof cb==='function')cb(false);},
    clear:function(id,cb){if(typeof cb==='function')cb(false);},
    getAll:function(cb){if(typeof cb==='function')cb({});},
    getPermissionLevel:function(cb){if(typeof cb==='function')cb('denied');},
    onClosed:_event,onClicked:_event,onButtonClicked:_event,onShowSettings:_event
  };}
  if(!chrome.privacy){chrome.privacy={
    network:{webRTCIPHandlingPolicy:{get:function(d,cb){if(typeof cb==='function')cb({},_noop);},set:function(d,cb){if(typeof cb==='function')cb();}}},
    services:{},websites:{}
  };}
  if(!chrome.declarativeNetRequest){chrome.declarativeNetRequest={
    updateDynamicRules:function(){return Promise.resolve();},
    getDynamicRules:function(){return Promise.resolve([]);},
    updateSessionRules:function(){return Promise.resolve();},
    getSessionRules:function(){return Promise.resolve([]);},
    onRuleMatchedDebug:_event
  };}
})();
`;

const STUB_SENTINEL = '// __devlens_electron_patched__';

/**
 * Patch a MV3 extension's service-worker file to prepend no-op stubs for
 * Chrome APIs that Electron does not implement.  Idempotent (checks sentinel).
 *
 * Also patches MV2 background scripts via the same approach when they live
 * in the `background.scripts` field.
 */
function patchExtensionForElectron(extDir: string): void {
  try {
    const mfPath = path.join(extDir, 'manifest.json');
    if (!fs.existsSync(mfPath)) return;
    const mf = JSON.parse(fs.readFileSync(mfPath, 'utf8')) as {
      manifest_version?: number;
      background?: {
        service_worker?: string;
        scripts?: string[];
        page?: string;
      };
    };

    const filesToPatch: string[] = [];

    if (mf.manifest_version === 3 && mf.background?.service_worker) {
      filesToPatch.push(path.join(extDir, mf.background.service_worker));
    } else if (mf.manifest_version === 2) {
      if (mf.background?.scripts) {
        // Only patch the first script — it runs first
        const first = mf.background.scripts[0];
        if (first) filesToPatch.push(path.join(extDir, first));
      } else if (mf.background?.page) {
        // background page: we'll use the dom-ready injection for HTML pages
      }
    }

    for (const target of filesToPatch) {
      if (!fs.existsSync(target)) continue;
      const existing = fs.readFileSync(target, 'utf8');
      if (existing.startsWith(STUB_SENTINEL)) continue; // already patched
      fs.writeFileSync(target, ELECTRON_COMPAT_STUB + '\n' + existing, 'utf8');
      console.log('[ext] Patched for Electron compatibility:', path.relative(extDir, target));
    }
  } catch (e) {
    console.warn('[ext] patchExtensionForElectron failed:', e);
  }
}

/**
 * Resolve a Chrome extension i18n message key (e.g. "__MSG_extName__") by
 * reading the extension's _locales directory. Returns the raw value if the
 * key cannot be resolved (no __MSG__ wrapper or locale file missing).
 */
function resolveI18nMessage(raw: string, extDir: string): string {
  const match = raw.match(/^__MSG_(\w+)__$/);
  if (!match) return raw;
  const key = match[1];

  const tryLocale = (locale: string): string | null => {
    try {
      const msgFile = path.join(extDir, '_locales', locale, 'messages.json');
      if (!fs.existsSync(msgFile)) return null;
      const messages = JSON.parse(fs.readFileSync(msgFile, 'utf8')) as Record<
        string,
        { message?: string }
      >;
      return messages[key]?.message ?? null;
    } catch {
      return null;
    }
  };

  // Prefer English, fall back to any available locale
  for (const locale of ['en', 'en_US', 'en_GB']) {
    const resolved = tryLocale(locale);
    if (resolved) return resolved;
  }
  try {
    const localesDir = path.join(extDir, '_locales');
    if (fs.existsSync(localesDir)) {
      for (const locale of fs.readdirSync(localesDir)) {
        const resolved = tryLocale(locale);
        if (resolved) return resolved;
      }
    }
  } catch {
    /* ignore */
  }

  return raw; // return the raw key if nothing resolved
}

export interface InstalledExtensionInfo {
  id: string;
  name: string;
  version: string;
  description: string;
  iconDataUrl: string | null;
  /** Relative path to the extension popup page, or null if the extension has none. */
  popupPath: string | null;
}

/** Returns true if the extension is already on disk (regardless of load state). */
export function isExtensionInstalled(extensionId: string): boolean {
  if (!/^[a-z]{32}$/.test(extensionId)) return false;
  return fs.existsSync(path.join(extensionsDir(), extensionId));
}

function readExtensionInfo(extDir: string): Omit<InstalledExtensionInfo, 'id'> {
  try {
    const mf = JSON.parse(fs.readFileSync(path.join(extDir, 'manifest.json'), 'utf8')) as {
      name?: string;
      version?: string;
      description?: string;
      icons?: Record<string, string>;
      browser_action?: { default_popup?: string };
      action?: { default_popup?: string };
    };

    const name = mf.name ? resolveI18nMessage(mf.name, extDir) : path.basename(extDir);
    const version = mf.version ?? '';
    const description = mf.description ? resolveI18nMessage(mf.description, extDir) : '';

    // Read the smallest usable icon as a base64 data URL
    let iconDataUrl: string | null = null;
    if (mf.icons) {
      const preferredSizes = ['48', '32', '128', '16'];
      const allPaths = [
        ...preferredSizes.map((s) => mf.icons![s]).filter(Boolean),
        ...Object.values(mf.icons).filter(
          (p) => !preferredSizes.map((s) => mf.icons![s]).includes(p),
        ),
      ];
      for (const iconRelPath of allPaths) {
        try {
          const buf = fs.readFileSync(path.join(extDir, iconRelPath));
          const ext = path.extname(iconRelPath).toLowerCase();
          const mime =
            ext === '.png'
              ? 'image/png'
              : ext === '.jpg' || ext === '.jpeg'
                ? 'image/jpeg'
                : 'image/png';
          iconDataUrl = `data:${mime};base64,${buf.toString('base64')}`;
          break;
        } catch {
          /* try next */
        }
      }
    }

    const popupPath = mf.action?.default_popup ?? mf.browser_action?.default_popup ?? null;

    return { name, version, description, iconDataUrl, popupPath };
  } catch {
    return {
      name: path.basename(extDir),
      version: '',
      description: '',
      iconDataUrl: null,
      popupPath: null,
    };
  }
}

/**
 * Return metadata for every extension installed on disk.
 */
export function listInstalledExtensions(): InstalledExtensionInfo[] {
  const dir = extensionsDir();
  if (!fs.existsSync(dir)) return [];

  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => ({ id: d.name, ...readExtensionInfo(path.join(dir, d.name)) }));
}

/**
 * Remove an installed extension from disk.
 * The caller is responsible for restarting the app or reloading sessions so
 * the extension is fully unloaded (Electron has no unloadExtension API).
 */
export function removeInstalledExtension(extensionId: string): void {
  if (!/^[a-z]{32}$/.test(extensionId)) throw new Error('Invalid extension ID');
  const extDir = path.join(extensionsDir(), extensionId);
  if (!fs.existsSync(extDir)) throw new Error('Extension not found');
  fs.rmSync(extDir, { recursive: true, force: true });
}

/**
 * Download and install a Chrome extension by ID.
 * Returns the resolved extension display name.
 */
export async function installChromeExtension(
  extensionId: string,
  sessions: Session[],
): Promise<string> {
  const extDir = path.join(extensionsDir(), extensionId);

  if (!fs.existsSync(extDir)) {
    const crxBuf = await fetchWithRedirects(crxDownloadUrl(extensionId));
    const zipBuf = crxToZip(crxBuf);
    fs.mkdirSync(extDir, { recursive: true });
    const zip = new AdmZip(zipBuf);
    zip.extractAllTo(extDir, true);
  }

  // Patch missing Chrome APIs before Electron loads the extension
  patchExtensionForElectron(extDir);

  const { name } = readExtensionInfo(extDir);

  for (const ses of sessions) {
    await loadExtensionIntoSession(ses, extDir);
  }

  return name;
}

/**
 * True if this session already has the extension (by id or install folder name).
 * Electron's `getExtension(id)` can return null even when the extension is
 * registered; `getAllExtensions()` + `path` basename is the reliable check.
 */
export function sessionContainsExtension(ses: Session, extensionId: string): boolean {
  if (!/^[a-z]{32}$/.test(extensionId)) return false;
  try {
    if (ses.extensions.getExtension(extensionId)) return true;
    for (const e of ses.extensions.getAllExtensions()) {
      if (e.id === extensionId) return true;
      const folder = path.basename(e.path.replace(/[/\\]+$/, ''));
      if (folder === extensionId) return true;
    }
  } catch {
    /* ignore */
  }
  return false;
}

/** Load from disk into `ses` if missing (e.g. popup window / new partition). */
export async function ensureExtensionLoadedInSession(
  ses: Session,
  extensionId: string,
): Promise<void> {
  if (!/^[a-z]{32}$/.test(extensionId)) return;
  if (sessionContainsExtension(ses, extensionId)) return;
  const extDir = path.join(extensionsDir(), extensionId);
  if (!fs.existsSync(extDir)) return;
  await loadExtensionIntoSession(ses, extDir);
}

/**
 * Load a single extension directory into a single session.
 *
 * Uses `session.extensions.loadExtension` (Electron 28+ non-deprecated API).
 * Skips silently if the extension is already loaded into this session to
 * prevent duplicate warnings caused by the race between SESSION_INIT calls
 * from the renderer and the startup `loadAllInstalledExtensions` sweep.
 */
async function loadExtensionIntoSession(ses: Session, extDir: string): Promise<void> {
  try {
    const extId = path.basename(extDir);
    if (sessionContainsExtension(ses, extId)) return;
    await ses.extensions.loadExtension(extDir, { allowFileAccess: true });
  } catch (e) {
    console.warn('[ext] loadExtension failed:', path.basename(extDir), e);
  }
}

/**
 * On app startup, re-load every previously installed extension into the given
 * sessions. Each session only receives each extension once.
 */
export async function loadAllInstalledExtensions(sessions: Session[]): Promise<void> {
  const dir = extensionsDir();
  if (!fs.existsSync(dir)) return;

  const entries = fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => path.join(dir, d.name));

  for (const extPath of entries) {
    patchExtensionForElectron(extPath);
    for (const ses of sessions) {
      await loadExtensionIntoSession(ses, extPath);
    }
  }
}
