/** CSS variables defined in `styles.scss` presets; cleared before applying custom overrides. */
export const THEME_CSS_VARIABLE_KEYS: readonly string[] = [
  '--dl-bg-base',
  '--dl-bg-surface',
  '--dl-bg-elevated',
  '--dl-border',
  '--dl-border-strong',
  '--dl-text',
  '--dl-muted',
  '--dl-accent',
  '--dl-accent-muted',
  '--dl-tab-active-bg',
  '--dl-success',
  '--dl-warning',
  '--dl-danger',
  '--dl-radius',
  '--dl-space-1',
  '--dl-space-2',
  '--dl-space-3',
  '--dl-space-4',
  '--dl-topbar-height',
  '--dl-sidebar-width',
  '--dl-right-sidebar-width',
  '--dl-shadow',
  '--dl-motion',
] as const;
